using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraScript : MonoBehaviour
{
    public GameObject target;
    public Out outed;
    public PlayerControllerFreeCameraVer playerController;

    //å£åˆ¤å®š
    public LayerMask fall;

    bool lookUp = false;

    float thardAxis;

    float rad = 0f;

    bool cameraIntelFlag = false;

    //å‘¨ã‚Šã‚’è¦‹æ¸¡ã›ã‚‹ã‹ã©ã†ã‹ã®ãƒ•ãƒ©ã‚°
    bool canMove;

    Vector3 num;
    float y;

    Vector3 initialCoor;

    Vector3 initialRolate;

    //å£ç”¨
    float rayCastSize;
    Ray ray;
    RaycastHit hit;
    MeshRenderer mesh;
    float red, green, blue;

    // Start is called before the first frame update
    void Start()
    {
        float z = Mathf.Pow(transform.position.z, 2) - Mathf.Pow(target.transform.position.z, 2);
        float y = Mathf.Pow(transform.position.y, 2) - Mathf.Pow(target.transform.position.y, 2);

        initialCoor = new Vector3(transform.position.x, y, z);
        initialRolate = transform.localEulerAngles;

        //ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‹ã‚‰ã‚«ãƒ¡ãƒ©ã¾ã§ã®æ–œè¾ºã®é•·ã•ã‚’æ±‚ã‚ã‚‹
        //â†‘ã‚«ãƒ¡ãƒ©ã®ä½ç½®ãŒæ¯ãƒ©ã‚¦ãƒ³ãƒ‰é•ã†ã®ã§å®šæ•°ã«ã—ã¾ã—ãŸã€‚
        rayCastSize = 10;

        transform.position = new Vector3(target.transform.position.x + 10 * Mathf.Sin(rad * Mathf.Rad2Deg), target.transform.position.y + 6, target.transform.position.z - 10 * Mathf.Cos(rad * Mathf.Rad2Deg));
        canMove = false;
    }

    //å¤§é™¸ã•ã‚“ãŒçµ„ã¿ã¾ã—ãŸ(ï½151ã¾ã§)
    private void LateUpdate()
    {
        thardAxis = Input.GetAxis("Cross_Horizontal");

        //rad += -thardAxis * 0.001f;
        transform.position = new Vector3(target.transform.position.x + 10 * Mathf.Sin(rad * Mathf.Rad2Deg), target.transform.position.y + 6, target.transform.position.z - 10 * Mathf.Cos(rad * Mathf.Rad2Deg));
        if (!lookUp)
        {
            transform.LookAt(target.transform);
        }
        else 
        {
            transform.eulerAngles = new Vector3(transform.eulerAngles.x - .0f, 0.0f, 0.0f);
        }

        //switch (turnCount)
        //{
        //    case 0:
        //        //transform.LookAt(target.transform.position);
        //        //transform.rotation = Quaternion.Euler(30f, 0 + 30f * crossHorizontal, 0);
        //        //transform.position = new Vector3(target.transform.position.x, target.transform.position.y + 3, target.transform.position.z - 5);
        //        break;
        //    case 1:
        //        //transform.LookAt(target.transform.position);
        //        //transform.rotation = Quaternion.Euler(30f, 90f + 30f * crossHorizontal, 0);
        //        //transform.position = new Vector3(target.transform.position.x - 5, target.transform.position.y + 3, target.transform.position.z);
        //        break;
        //    case 2:
        //        //transform.LookAt(target.transform.position);
        //        //transform.rotation = Quaternion.Euler(30f, 180f + 30f * crossHorizontal, 0);
        //        //transform.position = new Vector3(target.transform.position.x, target.transform.position.y + 3, target.transform.position.z + 5);
        //        break;
        //    case 3:
        //        //transform.LookAt(target.transform.position);
        //        //transform.rotation = Quaternion.Euler(30f, -90f + 30f * crossHorizontal, 0);
        //        //transform.position = new Vector3(target.transform.position.x + 5, target.transform.position.y + 3, target.transform.position.z);
        //        break;
        //}
        //transform.localPosition = initialCoor;//new Vector3(0, 3, - 5);
        //bï¿½{ï¿½^ï¿½ï¿½ï¿½ğ„‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ôï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×‚Ìƒtï¿½ï¿½ï¿½Oï¿½ğ—§‚Ä‚ï¿½
        //if (Input.GetButton("BtoE"))
        //{
        //    lookUp = true;
        //}
        //else
        //{
        //    lookUp = false;
        //}

        //if (Input.GetButtonDown("AtoQ"))
        //{
        //    turnCount++;
        //    if (turnCount == 4)
        //    {
        //        turnCount = 0;
        //    }
        //}
    }
    
    void FixedUpdate()
    {
        if (canMove)
        {
            rad += -thardAxis * 0.001f;
        }
        if (false)//outed.outArea)
        {
            lookUp = false;
            transform.LookAt(target.transform);
            num = transform.position;
            num.y = 0.0f;
            transform.position = num;

            cameraIntelFlag = true;
        }
        else
        {
            if (playerController.grounded)
            {
                if (cameraIntelFlag)
                {
                    transform.localPosition = new Vector3(0.0f, 0.0f, 0.0f);
                    transform.localEulerAngles = initialRolate;
                    transform.localPosition = initialCoor;
                    cameraIntelFlag = false;
                }
            }

            if (lookUp)
            {
                cameraIntelFlag = true;
            }
        }
        //ã“ã“ã¾ã§å¤§é™¸ã•ã‚“

        //ã“ã“ã‹ã‚‰å¯ºæ—
        //ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®ç›®ã®å‰ã«å£ã‚’è¡¨ç¤ºã•ã›ãªã„ã‚ˆã†ã«ã™ã‚‹
        ray = new Ray(transform.position, transform.forward);

        //ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®å‰ã¾ã§ã«å½“ãŸã£ãŸã‚‰ãã®æ™‚ã ã‘è¡¨ç¤ºã—ãªã„(é€æ˜åº¦ä¸Šã’ã‚‹)
        if (Physics.Raycast(ray, out hit, rayCastSize, fall))
        {
            //print("hit");
            //ã™ã§ã«é€æ˜ãªã‚‚ã®ãŒã‚ã£ãŸã‚‰è¡¨ç¤ºã—ç›´ã—
            if (mesh != null)
            {
                //é€æ˜åº¦ã‚’æœ€å°ã«ã™ã‚‹
                mesh.material.color = new Color(red, green, blue, 255);
                mesh = null;
            }
            mesh = hit.collider.gameObject.GetComponent<MeshRenderer>();
            //ã‚«ãƒ©ãƒ¼æ ¼ç´
            red = mesh.material.color.r;
            green = mesh.material.color.g;
            blue = mesh.material.color.b;
            //é€æ˜åº¦æœ€å¤§ã«ã™ã‚‹
            mesh.material.color = new Color(red, green, blue, 0);
            //mesh.enabled = false;
        }
        if (mesh != null && !Physics.Raycast(ray, out hit, rayCastSize, fall))
        {
            //é€æ˜åº¦ã‚’æœ€å°ã«ã™ã‚‹
            mesh.material.color = new Color(red, green, blue, 255);
            mesh = null;
        }

        //ãƒ‡ãƒãƒƒã‚°
        Debug.DrawRay(ray.origin, ray.direction * rayCastSize, Color.red);
    }

    void CanMove(bool flag)
    {
        canMove = flag;
    }
}

