using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//å¼¾ã«å½“ãŸã£ãŸæ™‚ã®ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ç­‰ã®å‡¦ç†ã¯å¯ºæ—(53ï½56ã€246ï½258è¡Œç›®)

public class PlayerControllerFreeCameraVer : MonoBehaviour
{
    enum Direction
    {
        None,
        Up,
        Right,
        Down,
        Left,
    }

    [Header("ãƒãƒ¼ã‚ºç”»é¢è¡¨ç¤ºã®æ™‚ã¯éŸ³ã‚’é³´ã‚‰ã•ãªã„")]
    public GameObject pouseObject;

    public AudioSource walksound;

    public GameObject animObject;
    Animator walkAnim;
    //ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Oï¿½iï¿½ï¿½ï¿½é‘¬ï¿½x 
    public float speed = 5f;

    //ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÌƒWï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½[
    float jumpPower = 0f;
    public float deltaJumpPower = 1f;
    public float jumpPowerMax = 32f;

    //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½]ï¿½ÌÛ‚Ìƒtï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½
    int movingFlameCount;

    //ï¿½nï¿½Ê‚É‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½Xï¿½|ï¿½[ï¿½ï¿½ï¿½nï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½ï¿½publicï¿½É‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½BC#ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½@ï¿½ï¿½ï¿½é‚©ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½)
    public bool grounded = false;

    public GameObject particle;

    public Transform groundPos;

    public LayerMask ground;

    //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Ìƒpï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ß‚Ä‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½
    bool isChargeJumpPower = false;
    //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‹lï¿½Ü‚ï¿½È‚ï¿½ï¿½æ‚¤ï¿½ÉˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×‚Ìƒtï¿½ï¿½ï¿½O
    bool isSpeed = false;
    //æ“ä½œå¯èƒ½ã‹ã©ã†ã‹
    bool OperationPossible = true;

    public bool canMove = false;

    //ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ 
    float coolTime = 0;
    [Header("æ•µã®çƒã«å½“ãŸã£ãŸã¨ãã®ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ")]
    public float coolTimePoint = 3.0f;

    //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½pï¿½ï¿½ï¿½[ï¿½iï¿½[ï¿½p
    Rigidbody rg;

    //ï¿½Eï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ÌŒï¿½ï¿½ï¿½
    Direction rightStickDirection;
    Direction rightStickDirectionOld;

    Direction rightStickRotateDirection = Direction.None;

    // Start is called before the first frame update
    void Start()
    {
        //ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½60ï¿½ÉŒÅ’è‚·ï¿½ï¿½
        Application.targetFrameRate = 60;
        //rigidbodyï¿½iï¿½[
        rg = gameObject.GetComponent<Rigidbody>();
        walkAnim = animObject.GetComponent<Animator>();
        walkAnim.speed = 0f;
        walksound = GetComponent<AudioSource>();
    }

    // Update is called once per frame
    void Update()
    {
        //ï¿½ï¿½ï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½Ì“ï¿½ï¿½Í’l
        float verticalLeft = Input.GetAxis("L_Vertical");
        float horizontalLeft = Input.GetAxis("L_Horizontal");

        //ï¿½Eï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½Ì“ï¿½ï¿½Í’l
        //float verticalRight = Input.GetAxis("R_Vertical");
        //float horizontalRight = Input.GetAxis("R_Horizontal");

        //ï¿½ï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½Â’nï¿½Ê‚É‚ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ì‚ï¿½(groundedï¿½ÌˆÓ–ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½Ä‚ï¿½ï¿½Ì‚ï¿½ifï¿½ï¿½ï¿½Å•ï¿½ï¿½ï¿½ï¿½Ä‚İ‚Ü‚ï¿½ï¿½ï¿½)
        if (grounded && OperationPossible && canMove)
        {
            //if (horizontalLeft < -0.5f || horizontalLeft > 0.5f || verticalLeft > 0.5f || verticalLeft < -0.5f)
            if (Mathf.Abs(new Vector2(verticalLeft, horizontalLeft).magnitude) > 0.5f) 
            {

                //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½XZï¿½ï¿½ï¿½Ê‚ÉŠÖ‚ï¿½ï¿½ï¿½Pï¿½Êƒxï¿½Nï¿½gï¿½ï¿½ï¿½ğ“¾‚ï¿½
                Vector3 playerForward = Vector3.Scale(Camera.main.transform.forward, new Vector3(1, 0, 1)).normalized;
                //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½Æ“ï¿½ï¿½Í’lï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ğ“¾‚ï¿½
                Vector3 moveForward = playerForward * -verticalLeft + Camera.main.transform.right * horizontalLeft;

                //ï¿½Ú“ï¿½
                rg.velocity = moveForward * speed;
                //ï¿½iï¿½sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                transform.rotation = Quaternion.LookRotation(moveForward);

                walkAnim.speed = 1f;

                //æ­©ãSE
                if (!walksound.isPlaying && !pouseObject.activeSelf)
                {
                    walksound.Play();
                }
            }
            else
            {
                rg.velocity = new Vector3(0.0f,0.0f,0.0f);
                walkAnim.speed = 0f;
                walksound.Stop();
            }
            //â†“ä½¿ã‚ãªããªã£ãŸ
            ////ã‚¸ãƒ£ãƒ³ãƒ—å‡¦ç†
            //if (verticalRight > 0.8f)
            //{
            //    isChargeJumpPower = true;
            //}

            //Debug.Log(rightStickDirection);
            //if (isChargeJumpPower)
            //{
            //    if (verticalRight > 0 && horizontalRight < 0.6)
            //    {
            //        rightStickDirection = Direction.Down;
            //    }
            //    else if (verticalRight < 0.6 && horizontalRight < 0)
            //    {
            //        rightStickDirection = Direction.Left;
            //    }
            //    else if (verticalRight < 0 && horizontalRight < 0.6)
            //    {
            //        rightStickDirection = Direction.Up;
            //    }
            //    else if (verticalRight < 0.6 && horizontalRight > 0)
            //    {
            //        rightStickDirection = Direction.Right;
            //    }
            //    else if (verticalRight < 0.6 && horizontalRight < 0.6)
            //    {
            //        //ï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö˜Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            //        rightStickDirection = Direction.None;
            //        rightStickRotateDirection = Direction.None;

            //        //ï¿½Eï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½tï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            //        isChargeJumpPower = false;
            //    }
            //}
        }

        //å¼¾ã«å½“ãŸã£ãŸã¨ãã®ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ 
        if(!OperationPossible)
        {
            coolTime += Time.deltaTime;
            rg.constraints = RigidbodyConstraints.FreezeAll;
            walkAnim.speed = 0f;
            if (coolTime > coolTimePoint)
            {
                //FreezeRotationZ,FreezeRotationXã‚’ã‚ªãƒ³ã«ã™ã‚‹
                rg.constraints = RigidbodyConstraints.FreezeRotationX | RigidbodyConstraints.FreezeRotationZ;
                OperationPossible = true;
                coolTime = 0.0f;
            }
        }
    }

    [System.Obsolete]
    private void FixedUpdate()
    {
        if (isChargeJumpPower)
        {
            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½pï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Å‘ï¿½lï¿½È‰ï¿½ï¿½Ìï¿½ï¿½Ì‚İƒpï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
            if (jumpPower < jumpPowerMax)
            {
                //ï¿½ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½Ä‚È‚ï¿½ï¿½ê‡
                if (rightStickRotateDirection == Direction.None)
                {
                    //ï¿½ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
                    if (rightStickDirection == Direction.Right)
                    {
                        rightStickRotateDirection = Direction.Left;
                    }
                    else if (rightStickDirection == Direction.Left)
                    {
                        rightStickRotateDirection = Direction.Right;
                    }
                }
                //ï¿½Eï¿½ï¿½]ï¿½Ìï¿½
                else if (rightStickRotateDirection == Direction.Right)
                {
                    //ï¿½ï¿½]ï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ê‡ï¿½pï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
                    if ((int)rightStickDirection == (int)rightStickDirectionOld % 4 + 1)
                    {
                        jumpPower++;
                    }
                }
                //ï¿½ï¿½ï¿½ï¿½]ï¿½Ìï¿½
                else
                {
                    //ï¿½ï¿½]ï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ê‡ï¿½pï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
                    if ((int)rightStickDirection % 4 == (int)rightStickDirectionOld - 1)
                    {
                        jumpPower++;
                    }
                }
            }

            //1ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Oï¿½ÌŒï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½Û‘ï¿½ï¿½ï¿½ï¿½ï¿½
            rightStickDirectionOld = rightStickDirection;
            //particle.GetComponent<ParticleSystem>().startLifetime = jumpPower * 0.5f;
            particle.GetComponent<ParticleSystem>().startSize = jumpPower * 0.5f;
        }
        else
        {
            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½[ï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½(rgï¿½ÉŠiï¿½[ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½)
            rg.AddForce(transform.TransformDirection(new Vector3(0, 2, 1)) * jumpPower * deltaJumpPower, ForceMode.Impulse);
            jumpPower = 0f;
            //particle.GetComponent<ParticleSystem>().startLifetime = 0f;
            //particle.GetComponent<ParticleSystem>().startSize = 0f;
        }

        if (Physics.Raycast(groundPos.position, Vector3.down, 0.1f, ground))
        {
            grounded = true;
            isSpeed = false;
        }
        else
        {
            grounded = false;
            if (!isSpeed)
            {
                rg.AddForce(transform.TransformDirection(new Vector3(0, 0, 2.0f)), ForceMode.Impulse);
                isSpeed = true;
            }
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        //ä½•å‡¦ã«ã“ã‚Œå…¥ã‚Œã‚ˆã†ã‹è¿·ã£ãŸã®ã§ã“ã“ã«ç½®ã„ã¨ãã¾ã—ãŸ
        if (other.tag == "shotBall" && OperationPossible)
        {
            //var rb = GetComponent<Rigidbody>();

            //Vector3 vector = gameObject.transform.position - other.transform.position;
            //rb.AddForce(vector.normalized * 6, ForceMode.Impulse);

            OperationPossible = false;
        }
    }

    void CanMove(bool CanMove)
    {
        canMove = CanMove;
    }
}